Repository Cactu5/recruitment-application, pull requests merged in 2021-02, with the labels that each got.

#6 feature/workflow
  .github/workflows/ci-build.yml
  .github/workflows/ci-deploy.yml
  pom.xml
  system.properties
Labels: documentation

#3 Feature/configs
  .gitignore
  pom.xml
  src/main/java/se/kth/iv1201/group4/recruitment/config/RecruitmentConfig.java
  src/test/java/se/kth/iv1201/group4/recruitment/config/RecruitmentConfigTest.java
Labels: enhancement

#5 Feature/security configs
  pom.xml
  src/main/java/se/kth/iv1201/group4/recruitment/config/RecruitmentSecurityConfig.java
  src/test/java/se/kth/iv1201/group4/recruitment/config/RecruitmentSecurityConfigTest.java
Labels: enhancement

#7 Feature/login view
  pom.xml
  src/main/java/se/kth/iv1201/group4/recruitment/config/RecruitmentConfig.java
  src/main/java/se/kth/iv1201/group4/recruitment/config/RecruitmentSecurityConfig.java
  src/main/java/se/kth/iv1201/group4/recruitment/presentation/error/ExceptionHandlers.java
  src/main/java/se/kth/iv1201/group4/recruitment/presentation/login/LoginController.java
  src/main/java/se/kth/iv1201/group4/recruitment/presentation/login/LoginForm.java
  src/main/java/se/kth/iv1201/group4/recruitment/presentation/register/RegisterController.java
  src/main/java/se/kth/iv1201/group4/recruitment/presentation/register/RegisterForm.java
  src/main/resources/application.properties
  src/main/resources/i18n/ValidationMessages.properties
  src/main/resources/log4j.properties
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/test/java/se/kth/iv1201/group4/recruitment/config/RecruitmentConfigTest.java
  src/test/java/se/kth/iv1201/group4/recruitment/presentation/login/LoginFormTest.java
  src/test/java/se/kth/iv1201/group4/recruitment/presentation/login/LoginViewTest.java
  src/test/java/se/kth/iv1201/group4/recruitment/presentation/register/RegisterViewTest.java
Labels: enhancement

#14 Feature/thymeleaf
  src/main/resources/i18n/Messages.properties
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/heading.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/test/java/se/kth/iv1201/group4/recruitment/presentation/login/LoginViewTest.java
  src/test/java/se/kth/iv1201/group4/recruitment/presentation/register/RegisterViewTest.java
Labels: enhancement

#20 Feature/javadocs
  src/main/java/se/kth/iv1201/group4/recruitment/domain/Applicant.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/Availability.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/Competence.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/CompetenceProfile.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/JobApplication.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/JobStatus.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/Person.java
  src/main/java/se/kth/iv1201/group4/recruitment/domain/Recruiter.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/ApplicantDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/AvailabilityDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/CompetenceDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/CompetenceProfileDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/JobApplicationDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/JobStatusDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/PersonDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/dto/RecruiterDTO.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/ApplicantRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/AvailabilityRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/CompetenceProfileRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/CompetenceRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/JobApplicationRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/JobStatusRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/PersonRepository.java
  src/main/java/se/kth/iv1201/group4/recruitment/repository/RecruiterRepository.java
Labels: documentation

#17 Feature/readme
  CONTRIBUTING.md
  README.md
  img/backend.png
  img/db.png
Labels: documentation

#23 feature/analysis
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  .github/workflows/ci-build.yml
  .github/workflows/remove-old-artifacts.yml
  README.md
  pom.xml
  src/main/resources/log4j.properties
Labels: test
